version: '3'
services:
  app:
    container_name: bio-app
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
     - 8000:8001
    depends_on:
     - db
    networks:
      - backend
    
  db:
    container_name: postgres
    image: postgres:14
    ports:
     - 5432:5432

    environment:
      - POSTGRES_USER=tior
      - POSTGRES_PASSWORD=tior123
      - POSTGRES_DB=database_qpa_project
    networks:
      - backend

networks:
  backend:
    driver: bridge