FROM python:latest

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt


COPY . /usr/src/app/
COPY ./scripts /usr/src/app/
COPY ./data/model.py /usr/src/app/
COPY ./data/config.py /usr/src/app/
COPY ./data/operations_db.py /usr/src/app/

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
